sudo: required
services:
  - docker
before_install:
  - docker build -t kdevelop/react-test -f ./client/Dockerfile.dev .
  
script:
  #- docker run kdevelop/docker_react npm run test -- -- coverage
  - docker run -e CI=true kdevelop/react-test npm run test

after_success:
  - docker build -t kdevelop/multi-client ./client
  - docker build -t kdevelop/multi-nginx ./nginx
  - docker build -t kdevelop/multi-server ./server
  - docker build -t kdevelop/multi-worker ./worker
# Log into the ducker CLI
  - echo $DOCKER_PASSWORD
  - echo $DOCKER_ID"
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --passowrd-stdin
# TAKE THOSE IMAGES aND PUSH THEM TO DOCKER HUB
  - docker push kdevelop/multi-client
  - docker push kdevelop/multi-nginx
  - docker push kdevelop/multi-server
  - docker push kdevelop/multi-worker
  - ssh-agent -k